[project]
name = "mlb-elt-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-bigquery==1.9.2",
    "google-cloud-bigquery>=3.10.0,<4",
    "google-cloud-storage>=2.4,<3.2",
    "python-dotenv>=1.2.2",
    "requests>=2.33.1",
]
